name: Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Setup Dependencies
      run: |
        pip install -r requirements.txt
        conda install --channel=conda-forge pandoc
        conda install sphinx
        
    - name: Build and Commit
      run: |
        sphinx-build -b html docs/source docs
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
